### ISSUE TITLE
Basic integration not working

### ISSUE THREAD

**Issue by theocodes** [bodrovis/lokalise_rails#13]
**Describe the bug**

Hi there,
We are currently testing the lokalise integration as a potential solution to translate our app and came across the following issue, wondering if you might be able to help.

`ArgumentError` when translating the following file:

```
en_GB:
  accounts:
    show:
      heading: Your Account
    update:
      failure: Unable to update your account, check the issues below
      success: Successfully updated your account
```

**To Reproduce**
Follow [this guide](https://docs.lokalise.com/en/articles/1558875-ruby-on-rails) to set up the gem and attempt to export the above using the rake task.

**Expected behavior**
No error

**Your environment:**
macOS 14.0
Ruby 3.1.4

**Additional context**
Also had to rename the top-level key from `en:` to `en_GB:` which is in itself not something I want to have to do but `en` alone caused another error:  ```RubyLokaliseApi::Error::BadRequest: Error while trying to upload [REDACTED]/en.yml: Invalid `lang_iso` parameter```
